services:
  mongodb:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - db_volume:/data
  backend:
    image: hakimbackend
    ports:
      - '3001:2077'
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
  frontend:
    image: hakimfrontend
    ports:
      - '8080:5173'
    env_file:
      - ./frontend/.env

volumes:
  db_volume:
